# Generated by Django 2.2.5 on 2020-06-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200621_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
